export enum AllowedLegalDocNames {
  DISCLAIMER = 'DISCLAIMER',
  EULA = 'EULA',
  INSTRUCTIONS = 'INSTRUCTIONS',
  NOTICE = 'NOTICE',
  PRIVACY = 'PRIVACY',
  SBOM_POINTER = 'SBOM_POINTER',
  SECURITY = 'SECURITY',
  SUPPORT = 'SUPPORT',
  THIRD_PARTY_LICENSES = 'THIRD_PARTY_LICENSES'
}
